# Site settings
title: Living Life Together
email: rebecca.eto@outlook.com
description: "Living Life Together"
baseurl: "rebeccaeto/rebeccaeto.github.io/"
url: "https://rebeccaeto.github.io/"
twitter_username: SBootstrap
github_username:  rebeccaeto
facebook_username:  rebeccaeto

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
