# Site settings
title: Living Life Together
email: rebecca.eto@outlook.com
description: "A blog featuring the Eto family adventures!"
baseurl: ""
url: "https://rebeccaeto.github.io/"
twitter_username: SBootstrap
github_username:  rebeccaeto
facebook_username:  becky.carpenter.167

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

